# Generated by Django 5.1.6 on 2025-03-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_text'),
    ]

    operations = [
    ]
